CREATE DATABASE useracc_;

use useracc_;

CREATE TABLE IF NOT EXISTS users (
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(30) NOT NULL,
	lastname VARCHAR(30) NOT NULL,	
	email VARCHAR(50) NOT NULL UNIQUE KEY,
	location VARCHAR(50),
    username VARCHAR(255) NOT NULL UNIQUE KEY,
    password VARCHAR(64) NOT NULL,
	date TIMESTAMP
);